### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by DewDropTales** [VinceDerPrince/World-Population-API#1]
Hey how are you,
I am working on a website and I need this api to for my calculation but I can not get it to work I've tried so much but I can't figure it out, uvicorn won't work and the virtual environment gives me errors. I just need it for the current world population so my code can have a live calculation. please help me if you can.

**Comment by VinceDerPrince** [comment]
Hi DewDropTales,

Thanks for reaching out! I appreciate your interest in the project. However, I must inform you that this project is discontinued as it was initially created for personal skill improvement, and I'm no longer actively maintaining it.

I want to make you aware that the code relies on Selenium, which might not be the most efficient choice for a website due to its relatively slower implementation. If you still wish to use the code, please ensure to update the file path in the scraper file to match your environment.

Keep in mind that using this "API" for live calculations on a website might have performance implications. You might want to explore alternative APIs or methods for fetching real-time data, considering the speed requirements for a website.

If you encounter any further issues or have additional questions, feel free to ask. Best of luck with your project!

Best regards,
Vince
